openmobilityfoundation/mobility-data-specification

- provider/README.md
I made three suggested additions to the provider API:
- trip/accuracy: For both technical (GPS accuracy limitations) and privacy (deliberate blurring of location information), the start/end point information may have limited accuracy. This flag allows data consumers to understand the limitations of the data reported. This presumes blurring will by done by a fixed radius. We may need to expand this to support blurring by geographic area (e.g. census block group). 
- trip/parking_verification: Many dockless providers request a photo of the parked vehicle from the user to verify correct parking. This field could be used to provide access to the photos to agencies for spot checks or other monitoring.
- availability/allowed_placement: A boolean to indicate whether the provider believes the …
> Suggested API additions

- provider/README.md
per @sfmta suggestion, this pull request changes the `availability` endpoint to a `status-change` endpoint.
I like this approach because it replaces a computed event (the amount of time a device was on a street) with an event. Events we can then compute into metrics.
> Changes Avaliability Endpoint to Status Change

- agency/README.md
> Removed HTML tags

- provider/README.md
This  change replaces `start_point`, `end_point` and associated field with `routes`, a new datatype which is a `geojson` list of points to represent the route a device took during a trip.
> New Routes Implementation.  fixes #19

- agency/README.md
- provider/README.md
Suggesting a change to the identifier for a vehicle away from a UUID and using the operators VIN identifier instead.   The thought here is that each bike manufacturer already has a unique identifier for their vehicle embedded in their code (QR code or otherwise).  It is inherent to the business.   Let's use that number so they could be correlated to real bikes on the street if it ever became necessary.
> Change device_id to VIN

- agency/README.md
- provider/README.md
It doesn't make sense to have all the responses use snake case (underscores) with endpoints with dashes.
Partially because consistency but also because most web frameworks use underscores. The only one I'm aware of that uses dashes is Django, and [that seems somewhat contentious](https://medium.com/@raiderrobert/django-url-names-should-be-underscore-separated-7815e3d4e7c2)
> Consistency in underscores

- agency/README.md
Last minute change to make a message more accurate.
> Update to Vehicle_Registry message

- README.md
- agency/README.md
This PR adds response and body text  to the `service_area` Agency endpoint. It also deletes a typo when the endpoint was moved from agency to provider.
> Fixing the service area bug in agency

- provider/README.md
Just a small suggestion that it might be useful to distinguish between completely electric vehicles (like Lime and Bird Scooters) and pedal assist vehicles that combine human and electric power (like Jump bikes).
I added `electric_assist` to the `propulsion_type` enum to fix this.
I understand if you want to call both of these kinds of vehicles `electric`, but I think the distinction could be useful!
> Adding electric_assist as a propulsion_type.

- providers.csv
This pull request adds an empty provider csv file for each operator to add in a PR. 
Each company should provide their name, a UUID ID, url, and their MDS url in a following PR.
> Adding providers.csv. fixes #39

- agency/README.md
Per discussion in #78, all endpoints for GET requests should only accept
request parameters via the query string in the URL. While #64 clarifies
this for the Provider API, this updates the only GET endpoint in the
Agency API.
> Clarify that /service_areas endpoint takes query parameters.

- provider/README.md
- provider/auth.md
Provide information on authentication with JWT and minimal payload.
Update provider/README.md to reference auth.md
Refs Issue [#60](https://github.com/CityOfLosAngeles/mobility-data-specification/issues/60)
> Add auth.md to document provider authentication

- provider/README.md
For trips and status_changes break query params
out into their own section.
Add more detail around how to specify time
and location based parameters.
For location this is just a suggestion.
There may be url length concerns when passing in large polygons
in query params.
A better approach might be to pass in service_area id or
use a location filter based on the token and
filter data further after retrieval
Comments welcome.
> Add detail to query params for providers

- README.md
Previous link went to LADOT's YouTube page; current one goes directly to actual presentation
> Fixed video link

- provider/README.md
Pull request #53 removed the indication that the `trips` and `status_changes` endpoints return an array of objects, but kept the object definitions inline.
We propose to add back the array definitions, which is our preference and is implemented in this pull request, or to remove the markdown versions of the object definitions from the spec.
> Add back array definitions

- agency/README.md
- provider/README.md
We were using the undocumented two-trailing-spaces method to do line breaks in some places. Line breaks were missing in other places. Trailing spaces are not handled well in some editors, and Git likes to whine about trailing whitespace. Replace with backslashes and add missing. Backslashes are also non-standard and undocumented, unfortunately.
> Standardize line breaks

- provider/README.md
Suggesting moving the real-time feed from a subsection of the Trips endpoint to its own section to clarify that it is a separate requirement with a separate endpoint
> Elevating Status of Realtime Feed

- provider/README.md
This is a suggestion to add some additional clarification around propulsion types, mainly the difference between `electric_assist` and [`human`, `electric`]. I've seen a couple of provider APIs submitted that have the former when it should be the latter. I think that #48 did a great job of explaining why this should be represented as an array, but that reasoning is not reflected in the current MDS spec.
> Suggestion: Add Clarification to Propulsion Types

- generate_schema/common.json
- provider/status_changes.json
- provider/trips.json
`links` itself is still optional, this just clarifies that the only required `links` property is `next`.
> Allowing for null links properties

- README.md
This PR changes some of the language in README to clarify between agency, provider, and how to implement. It also removes some CityOfLA specific phrasing.
> Agency vs Provider Clarification. [#148]

- generate_schema/common.json
- provider/status_changes.json
- provider/trips.json
> Allowing null for links.next

- provider/auth.md
In previous discussions (linked below) about authenticating MDS requests, there was a preference for not prescribing a specific authentication method. While there are benefits to the MDS protocol definition remaining process-agnostic and not prescriptive, the immediate drawbacks are that cities and data partners struggle to maintain multiple authentication schemes and mobility providers do not have alignment on security best practices for authorization to access MDS data.
In this PR, I propose specifying the OAuth2.0 `client_credentials` grant type as a way to alleviate this. In this auth scheme, a client secret is given by a mobility provider to a city, who can then use it to generate access tokens via the provider’s OAuth2.0 service in a repeatable, documented way. These tokens are …
> Add OAauth client_credentials auth guidelines section

- provider/README.md
Addresses part of #165, by adding an explicit requirement to the README that paginated payloads should include a `next` key at a minimum.
> Add `next` link requirement

- agency/README.md
- provider/README.md
We propose adding the following functionality to the Service Area API.  The agency API would allow agencies to also indicate restricted zones and preferred pick-up/drop-off zones.  We envision this as a mechanism to communicate both permanent and temporary (e.g., special event) prohibited/incentive zones, rather than ad-hoc communications (e.g., emailing a shapefile).
We presume the providers also have their own prohibited/incentive zones.  The Provider API would return the full set of prohibited/incentive zones (whether indicated by the provider or the agency).
>  Add service area type to the agency API. Add service areas to the provider API

- generate_schema/Pipfile
- generate_schema/Pipfile.lock
- generate_schema/common.json
- generate_schema/generate_provider_schema.py
- generate_schema/provider/status_changes.json
- generate_schema/provider/trips.json
- provider/README.md
- provider/status_changes.json
- provider/trips.json
This PR reverts all changes made in PR #146, so that we don't merge the milliseconds since epoch unix timestamp feature. This is paired with PR #179, which cherry-picked those changes. If we squash and merge this, we can cut version 0.2.1.
> Revert 146

- generate_schema/generate_provider_schema.py
- provider/status_changes.json
- provider/trips.json
Remove the GeoJSON Feature `oneOf` allowance for properties when we are setting the required field. This makes the properties key itself required, and forces its type to object.
Ported from the #146/#179/#180 mess
> Fix for required properties in generated schema

- agency/README.md
This is a baseline restructure of the Agency api to address a number of endpoint changes and incorporate feedback received in previous issue and PRs (#161 , #116  and #63 ).
Major changes:
* `provider_id` is passed as part of an authorization bearer token.
* Looking up and registering vehicles use standard `GET` and `POST` operations on `/vehicles` endpoint.
* The `/vehicles/{vehicle_id}/event` allows Providers to `POST` events to affect vehicle status.  The vehicle status is modeled around a state flow that is modeled in Vehicle Events table.
* Deregister vehicle, trip start and end are now events.
* Events for `trip_enter` and `trip_leave` were added to address trips that do not start or end in the Agency jurisdiction.
> Restructure api and add event-status model

- provider/README.md
I initially proposed #113, which was correctly pointed out as a dupe of #105. However, looking at the relevant PR #156 , it only addresses the agency spec without also addressing Provider. This adds (some) clarification around standard HTTP status codes for the provider part of #105.  
I think that we could also have some language encouraging providers to be as specific as possible in the error response code and to avoid 500 when possible, though maybe this is too much. Open to suggestions.
I added it under Response Format, but open to other ideas if there is a better placement elsewhere.
> Require Standard HTTP Status Codes for Provider

- generate_schema/provider/status_changes.json
- provider/README.md
- provider/status_changes.json
- provider/trips.json
I had some time, so I fixed up and rebased #202. Same fix, but with json schema fixes (it wasn't actually requiring `associated_trip`) and cleanup.
> Updated associated trip patch

- provider/README.md
`provider` APIs must support versioning going forward. As implemented
here, we will use a custom media-type to negotiate the API version a client
and server will use. A couple reasons for taking this approach:
* API versioning will become important as 0.3.0 and future releases are
published with breaking changes that Providers, cities and third-parties
will need to implement/adopt on differing timelines.
* Because this is a specification for others (Providers) to implement
their APIs against, mandating URI structure beyond endpoints could be
burdensome or limiting. Conversely, leveraging standard HTTP Headers in
a compliant manner places no limitations.
* Further, in practice, many providers have already begun implementing
their own versioning in their registered `mds_api_url`.
Closes …
> Add versioning requirement to Provider API

- provider/README.md
This allows providers to truncate the GPS to the maximum level of precision given the accuracy of whichever measurement system the use.
> Update provider to allow precision based truncate. fixes #209

- provider/README.md
In conversations and from ingesting data, it's become clear there is
ambiguity in how parties are reporting data in their MDS Provider API
implementations with respect to the boundary of the municipality they
are operating in. This commit adds some clarifications and definitions
to capture the original intent of the spec and what most cities (Santa
Monica and LA) have been expecting in this regard.
> [Provider] Clarify how endpoints relate to municipality boundaries.

- agency/README.md
Depending on the actual device on board of the vehicle,
some information can be unavailable.
> Relax telemetry constraints

- agency/README.md
also clean up some telemetry wording
This was requested by Bird.  They have cases where the vehicle-id gets scratched off by a vandal and a new (different) one is applied by their maintenance staff.
> add PUT /vehicles/{device_id}

- ReleaseGuidelines.md
- generate_schema/common.json
- provider/status_changes.json
- provider/trips.json
There's a step missing in the ReleaseGuidelines, and we forgot to update the schema version regex before releasing `0.3.0`. 
This updates the version and adds the step to ensure it isn't missed again.
> Updating schema version

- agency/README.md
Approved by LADOT on 4Feb2019.  Updated in-trip telemetry compliance for scooters.
> Compliance Patch - Telemetry Update

- providers.csv
BlueLA is an electric car sharing service in Los Angeles. We have implemented the MDS API and believe we are ready for inclusion in the list of providers.
I believe that we are the first service with *cars*. Apart from the vehicle type that we obviously had to customize (we use "car" for now [1]), we've been able to successfully implement the MDS (as well as the parts of GBFS that are mandated by the MDS).
[1] Speaking of the vehicle type, I have seen discussions about that, albeit much broader (and, as such, probably less actionable). I took the liberty of proposing #219 that adds a new `car` vehicle type.
> Add provider: BlueLA

- agency/README.md
In the case that none of the provided telemetry data is valid, respond with a 400 error. In the case that at least one of the provided data points is successfully processed, respond with a 201 specifying how many data points were successful out of the total, and a list of failed points (if there are any).
> Invalid telemetry data 400 res

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-request---proposal.md
- .github/pull_request_template.md
- ReleaseGuidelines.md
Per discussion on #270, this will help ensure that maintainers have the right information to tag issues and PRs with the correct milestones and labels. The information supplied about breaking/non-breaking changes will also be used to determine which release a given change should be targeted for.
> Initial check in of issue and PR templates

- ReleaseGuidelines.md
This commit modifies the branching mechanics in the release guidelines in
order to simplify the process of maintaining and contributing to MDS.
The most notable changes are:
* `dev` is now the target for almost all PRs, whether the changes they
contain are breaking or non-breaking. Maintainers are responsible for
backporting non-breaking changes from `dev` to the latest release
branch after merging the PR.
* Instead of merging changes into `master` and rebasing `dev`, `master`
is reset to point to the latest release as part of the release process.
Rebasing and merging between branches (other than PRs) are no longer
part of the process at all.
These changes are intended to be relatively lightweight and aimed at
smoothing out pain points with the current workflow; at some point we
might …
> Update branching process in release guidelines

- provider/README.md
This implements the change suggested in #289 by clarifying that any
trip-ending event can and should have an `associated_trip`, not just
`user_drop_off` events.
Since the Provider event system currently doesn't define which states
are allowed to transition to which other states, it's already
spec-compliant to follow a `reserved`/`user_pick_up` event with an
`unavailable`/`low_battery` event, and this is the most
semantically-accurate way to describe the scenario where a device shuts
down during a trip because of low battery. In this situation, the
implementer should include an `associated_trip` field in both events
so that API consumers can correctly identify these events as the
endpoints of the relevant trip.
**Is this a breaking change**
**`Provider` or `agency`**
> Explicitly allow `associated_trip` for any event type

- ReleaseGuidelines.md
This commit adds a section to the release guidelines doc clarifying the
distinction between breaking and non-breaking changes, including an
enumeration of what kinds of changes fall in each category. This builds
on language added in #286; I didn't modify those templates here since
their description of breaking vs. non-breaking is still accurate.
I think the most likely area of controversy here is the handling of enum
values. My inclination would actually be to treat changes to enum values
as breaking changes, but it seems like the consensus during the 0.3.1
process so far has been that the benefits of having a lightweight
process for updating enums outweigh the risk of breaking clients that
are doing stricter validations.
Fixes #279
**Is this a breaking change**
**`Provider` or `agency`**
> Flesh out definition of breaking vs. non-breaking changes

- ReleaseNotes.md
This PR adds the release notes for 0.3.1
> 0.3.1 release notes

- ReleaseNotes.md
Quick fix of the release notes for `0.3.1`.
> Fix ReleaseNotes merge conflict

- agency/README.md
- agency/post_vehicle_event.json
- agency/post_vehicle_telemetry.json
- generate_schema/common.json
- generate_schema/provider/status_changes.json
- provider/README.md
- provider/status_changes.json
I change every `GPS` by `GPS or GNSS` to include all [GNSS](https://en.wikipedia.org/wiki/GNSS_applications) (GLONASS, Galileo, BeiDou)
For more information you can see the issue:
#309 - GPS to GNSS (i18n)
both
To make it not breaking, I only edit the text and did not change any field.
> Agency/Provider: change 'GPS' by 'GPS or GNSS' except field. close #309

- provider/README.md
The specification has a vague statement about returning a list of available versions when the API returns a 406. Since we now have a standard way to negotiate versions, this PR updates the text to refer to that. This was discussed in the MDS provider specification meeting on 6/6/2019.
https://github.com/CityOfLosAngeles/mobility-data-specification/issues/313
> Update the 406 response when an invalid version is requested.

- provider/README.md
This proposal reflects the consensus of the status change ordering/uniqueness breakout group that it's reasonable to ask providers to construct an accurate and causally-consistent timeline of status
change events. This change will improve API consumers' ability to understand the ordering and timing of events in the status changes API.
See [the notes from the first breakout group call](https://groups.google.com/forum/#!topic/mds-announce/RcKFkpJ7qrA) for a little bit more context.
> Change `event_time` definition to require correct ordering

- provider/README.md
- provider/status_changes.json
- provider/trips.json
- schema/templates/provider/status_changes.json
- schema/templates/provider/trips.json
These fields will be optional in 0.3.2 and mandatory in a future version. They reflect the time that the provider made the relevant data available through the API.
This commit partially fixes #307, but it's not a complete fix since it doesn't include the ability to query by publication time.
* `provider`
The next minor version should make these fields mandatory and also add query params allowing clients to use them for filtering.
> Add `publication_time` fields to trips and status changes

- provider/dockless/status_changes.json
- schema/templates/provider/status_changes.json
PR #297 already updated the spec language to make it clear that any status change is allowed to have an `associated_trip`, but I didn't realize this was incompatible with the existing schema. The schema should now match the spec, which states that `user_pick_up` and `user_drop_off` events must have an `associated_trip` but other events may have one when applicable.
It's not really clear whether this should be considered a breaking change. I could see arguments either way, but I think it's moot if the intention is for this to be included in the 0.4.0 release.
`provider`
> Allow any status change to include an `associated_trip`

- provider/README.md
#226 clarified precisely what data providers are expected to return through the API, by requiring an unambiguous geography boundary:
> Municipalities requiring MDS Provider API compliance should provide an unambiguous digital source for the municipality boundary. This boundary must be used when determining which data each provider API endpoint will include.
> The boundary should be defined as a polygon or collection of polygons. The file defining the boundary should be provided in Shapefile or GeoJSON format and hosted online at a published address that all providers and provider API consumers can access and download.
The wording here could be interpreted to mean that providers need to apply the latest version of this municipality boundary to all queries. This interpretation prevents …
> Clarify municipality boundary geofiltering for historical data (#355)

- agency/post_vehicle_event.json
- agency/post_vehicle_telemetry.json
- provider/dockless/status_changes.json
- provider/dockless/trips.json
- schema/generate_schema.py
- schema/templates/common.json
Several telemetry fields lack input validation supported by json-schema. Currently, the API will accept invalid GPS coordinates. 
This change restricts telemetry GPS latitude and longitude values to be valid coordinates of [-90,90] for latitude and [-180,180] for longitude. JSON validation can reject malformed GPS coordinates rather than propagate bad data.
This is a **non-breaking change for code**.
It is a potentially **breaking change for legacy bad data** with invalid GPS coordinates. That's ultimately the intent. City agencies will need to assess whether there is a practical impact based on the quality of existing data.
This pull request impacts the **Agency API's** vehicle event and telemetry POST endpoints.
> Adding min and max values for GPS coordinates in common JSON schema

- provider/README.md
Hi, I'm Zak and I joined the team at Remix a few weeks ago. I'm excited to work with the MDS community!
In MDS Provider it is implied that all references to timestamps should be made using `milliseconds since unix epoch`. The sections of the provider `README` for query parameters do not explicitly state types for query parameters. This change formats the explanations of query parameters to match the table specification for returned data and explicitly set types for each parameter.
Providers who assumed the query parameter types were ambiguous may have to update their code if they were using `seconds since unix epoch` instead of `millisconds`.
Provider.
> Specify types for Provider query parameters

- ReleaseGuidelines.md
As per issue https://github.com/CityOfLosAngeles/mobility-data-specification/issues/364
I will need to add the meeting calendar URL to the PR before this can be merged.
* None
None
> Update ReleaseGuidelines.md with meeting info

- providers.csv
Please provide a clear and concise reason for this pull request and the impact of the change
> Add Provider VOI

- agency/README.md
The paragraph specifying latency and time/space resolution should never have been included in the spec.  Such requirements are policy decisions that should be adjudicated by regulating agencies.
Remove paragraph
* `agency`
None
> Remove SLA verbiage from /telemetry endpoint

- provider/README.md
From #317 
> Adopt same error responses as for Agency API
* `provider`
Nothing immediately comes to mind
> Unify error response format per #317

- provider/README.md
`Accept: */*` is used by very common prevalent clients like python requests and postman
important to note here when implementing versioning via accept headers to properly support client code
> [provider readme] fix version legacy headers

- agency/README.md
- agency/get_vehicle.json
- agency/post_vehicle.json
- schema/templates/agency/get_vehicle.json
- schema/templates/agency/post_vehicle.json
- schema/templates/common.json
Per #348:
> Is there a plan to add a field size limitation? For example, the device_id or vehicle_id could be limited in their number of characters.
* `agency`
> Add string limit length of 255

- provider/README.md
- provider/dockless/status_changes.json
- schema/templates/provider/status_changes.json
In #269, it is brought up that having a 311 or CRM case id to associate with particular status changes may be useful. This PR allows a status change to have a CRM case ID / associated ticket with it. 
* No, not breaking - optional field. 
* `provider`
> add associated_ticket. Fixes #269

- README.md
- agency/README.md
- agency/get_vehicle.json
- agency/post_vehicle.json
- provider/README.md
- provider/dockless/status_changes.json
- provider/dockless/trips.json
- schema/templates/common.json
I am working with BlueLA, a car sharing service in Los Angeles. We have implemented the MDS API. 
The MDS API currently has 2 types of vehicle: `bicycle` and `scooter`. I have seen discussions about adding new types (at least #95 #167 #170) but they seem to be stale and/or related to broader subjects (and thus less actionable).
I think that "just" adding a new `car` vehicle type could be an easy and good enough first step.
> Add "car" vehicle type

- provider/dockless/status_changes.json
- provider/dockless/trips.json
- schema/templates/common.json
Bumping the version number string in the common schema, regenerate dockless schemas.
Yes, `0.4.0` is a new version with breaking changes.
* `provider`
> Update JSON schemas for 0.4.0

- CODEOWNERS
This PR is part of #386, changes the CODEOWNERS structure to mirror OMF structure. 
* both
> update CODEOWNERS in prep for OMF move

- provider/README.md
In #268, @johnpena discusses the need to make MDS queries more predictable. @babldev attempted to address the issue in #354, but during the discussion on 9-4, it sounded like folks wanted a different type of solution. 
This builds on #354 and specifically @hyperknot's suggestion that we split the possible response with different query parameters. 
It introduces `static_end_time` to both `/trips` and `/status_changes`. This would be an ISO month, day, or hour that could be cached on S3 or a similar static file store that could be returned as a single page or set of pages. 
TBH, adding this complexity makes me want to also finish the openAPI work so that this can be made more clearly and testable by providers and clients alike. I'll take a stab at that shortly, but would love folks thoughts …
> Allow static file data storage for Provider /status_changes and /trips

- provider/README.md
Additional clarity for the recent static file changes #357.
* `provider`
> Provider language cleanup

- provider/README.md
- provider/dockless/trips.json
- schema/templates/provider/trips.json
This PR fixes a couple of bugs introduced in #379.
Firstly, the schema only allows integral costs; this is insufficient for many currencies that contain a fractional part (including USD). This PR changes the types of the cost fields to `number` instead of `integer`. Since `number` is a superset of `integer`, this should not break backwards compatibility.
Additionally, the wording does not specify the behavior when the `currency` field is not present. This change clarifies the language to use the old definition (cents of USD) to keep backwards compatibility.
* `provider`
> Add a section clarifying currency units; specify behavior when no currency is given

- policy/examples.md
This is simply to fix a typo in the example provided for the policy.
It will have no impact on the APIs
> Small typo in policy spec

- policy/README.md
Linking to relevant status tables in Agency and Provider for reference clarity.
* `policy`
> Add clarity on rule status field

- CODEOWNERS
As part of the code transfer from LADOT to OMF (#386), we are switching CODEOWNERS to use OMF's GitHub Teams, rather than individually naming maintainers. This PR should be merged as part of the code transfer process.
> Switch CODEOWNERS to use OMF teams

- LICENSE
The Open Mobility Foundation intends to license mobility-data-specification under the CC BY 4.0 License, rather than the CC0 1.0 license used by LADOT. After LADOT has transferred ownership of the mobility-data-specification repository to OMF (#386), we will commit this PR to effect the license change.
This is a non-breaking change, however, it may necessitate that people/organizations using this repository or building derivative products adjust their own licensing or documentation to comply with the requirements of CC BY 4.0, specifically section 3(a) - Attribution.
> Update license from CC0 to CC-BY (after transfer to OMF)

- README.md
- ReleaseGuidelines.md
- ReleaseNotes.md
- agency/get_vehicle.json
- agency/post_vehicle.json
- agency/post_vehicle_event.json
- agency/post_vehicle_telemetry.json
- provider/auth.md
- provider/dockless/status_changes.json
- provider/dockless/trips.json
- schema/templates/agency/get_vehicle.json
- schema/templates/agency/post_vehicle.json
- schema/templates/agency/post_vehicle_event.json
- schema/templates/agency/post_vehicle_telemetry.json
- schema/templates/common.json
- schema/templates/provider/status_changes.json
- schema/templates/provider/trips.json
Replace all instances in the repo of "cityoflosangeles/mobility-data-specification" with "openmobilityfoundation/mobility-data-specification" 
* `agency`
* `policy`
* `provider`
> replace URLs for move

- ReleaseGuidelines.md
There is a lingering reference to the original ML that is updated with this PR
N/A
N/A
> Correct reference to old mds-announce ML in the Release Guidelines

- provider/README.md
It clarifies that the static provider endpoints (/trips and /status_changes) should not have server-side pagination.
* `provider`
As one of the contributors who proposed the original static-file backed provider endpoint idea for /trips and /status_changes endpoints, I believe it's important that there should be no server-side pagination on the short time intervals. 
Longer …
> Clarify no pagination on static provider endpoints /trips and /status_changes

- CODEOWNERS
We simplified the OMF org team names. Updating the CODEOWNERS file to reflect these changes.
* `agency`
* `policy`
* `provider`
> Updating team names in CODEOWNERS

- policy/examples.md
Hello, just a small PR to update the example (Idle time) as it has `limit` where it should be `maximum` to configure the rule.
* `policy`
> Update example to use "maximum" instead of "limit"

- policy/README.md
- policy/examples.md
Hello, it seems that the property `rule_id` is missing in the description of the Rule. It makes sense to have one, and the examples have a rule_id.
* `policy`
> Add missing rule_id to rule in Policy spec

- agency/README.md
- general-information.md
- policy/README.md
- provider/README.md
This is a pull request attempting to solve #422 without introducing any breaking changes to the `provider` API.
* `agency`: adding versioning section
* `policy`: adding versioning section
* `provider`: moving the versioning section
None
> add versioning for Agency and Policy API

- provider/README.md
As discussed on the [2020-02-13 Provider Services call](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2020.02.13-(Provider-Services-WG)) we'd like to more easily identify which endpoints are required, which are optional, and any anticipated changes to this status.
* `provider`
> Making required/optional endpoints more explicit

- .github/pull_request_template.md
As discussed on the [2020/02/27 Provider Services call](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2020.02.27-(Provider-Services-wg)), this PR updates the PR template to remind folks to target the `dev` branch.
* N/A
> Add language around targeting dev branch

- provider/README.md
- provider/dockless/events.json
- provider/dockless/status_changes.json
- provider/dockless/trips.json
- provider/dockless/vehicles.json
- schema/generate_schemas.py
- schema/templates/common.json
- schema/templates/provider/status_changes.json
- schema/templates/provider/trips.json
- schema/templates/provider/vehicles.json
Some of the schema templates and subsequent builds listed incorrect URLs in their `$id` property. This PR fixes these and introduces small language cleanups.
Additionally, as of `0.4.1` the `/trips` and `/status_changes` endpoints do not allow paging, which is now reflected in their respective schemas. Since `/events` does support paging, a new schema has been introduced for that endpoint, based on the `/status_changes` schema.
* `provider`
> Schema fixes/updates

- .github/ISSUE_TEMPLATE/release-candidate-review.md
- CONTRIBUTING.md
- ReleaseGuidelines.md
This documentation update clarifies the approval process by which the Open Mobility Foundation certifies a release, and updates the release cycle timeline to 12 weeks (from its original 6).
> ReleaseGuidelines updates to reflect OMF process and 12 week dev cycle

- general-information.md
- provider/README.md
This pull request defines the idea of a "beta" feature and replaces the optional/required designation (#456) on the `provider` API endpoints with a beta yes/no designation.
This is a proposed change to the 0.4.1 release candidate that emerged from review by the OMF Technology Council. The concern identified by the Council is that "optional/required" does not clearly communicate if, when, and how an endpoint should be used. For example, is it OK for a regulator to ask a provider to implement an optional endpoint? For what purposes is it appropriate to use an optional endpoint?
The new "beta" language attempts to remove this ambiguity by honestly communicating what users can expect in terms of the completeness, quality, and stability of newly added features. Users can then make an informed …
> Define "beta" features and replace the optional/required designation for endpoints

- provider/README.md
Thank you for your contribution!
*For most Pull Requests, the target branch should be [**`dev`**](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev). Please ensure you are targeting **`dev`** to avoid complications and help make the Review process as smooth as possible.*
(Late Addition to the RC!)
We link to the `trips` and `status_changes` schemas in this section, adding links to the `events` and `vehicles` schemas as well.
* `provider`
> Adding links to events and vehicles schema files

- provider/README.md
Per Board of Directors discussion on 4/15, clarified language to indicate that `/vehicles` is for regulator use and does not replace the value of a GBFS feed for consumer facing-applications.
> Clarified that /vehicles is not intended to replace GBFS

- README.md
Thank you for your contribution!
*For most Pull Requests, the target branch should be [**`dev`**](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev). Please ensure you are targeting **`dev`** to avoid complications and help make the Review process as smooth as possible.*
Addresses [#9](https://github.com/openmobilityfoundation/privacy-committee/issues/9). Update the README with a link to the Mobility Data Management State of Practice wiki, managed by the Privacy, Security, and Transparency Committee.
None—README only.
The [Mobility Data Management State of Practice](https://github.com/openmobilityfoundation/privacy-committee/wiki/Mobility-Data-Management-State-of-Practice) was developed by the OMF's Privacy, Security, and Transparency …
> Add link to State of Practice Wiki

- provider/README.md
Since GBFS 2.0 is a thing and the language I wrote about GBFS and micromobility is out of date, this updates provider to require using GBFS 2.0 for overall implementation.
> Change GBFS references

- agency/README.md
Thank you for your contribution!
*For most Pull Requests, the target branch should be [**`dev`**](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev). Please ensure you are targeting **`dev`** to avoid complications and help make the Review process as smooth as possible.*
In several cities, the Agency is not connected directly to mobility providers. There is an aggregator in-between centralising the data from the providers and re-exposing them to the Agency.
When registering a device with the Agency API, there is currently no way for the aggregator to indicate which provider the device belongs to. This PR proposes a way to fix this.
A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: …
> Agency: vehicle register: add provider_id field

- agency/README.md
Some fields from the /vehicle endpoint cannot be provided because the provider did not provide them at registration (`year`, `mfgr`, `model`) or because no event has been pushed for the vehicle yet (`status`, `prev_event`, `updated`).
A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint).
* No, not breaking 
* `agency`
> Agency: clarify vehicle endpoint requirements

- agency/README.md
According to the RFC : https://tools.ietf.org/html/rfc7231#section-6.3.1
the HTTP response for an update (that does not create any object) can
either be 200 (OK) or 202 (ACCEPTED)
The later "indicates that the request has been
accepted for processing, but the processing has not been completed."
Since updating the vehicle_id should be quite fast, we should use a 200
response code.
* Yes, breaking (since providers may check the response code when sending data)
* `agency`
> agency: Vehicle Update response code should be 200

- policy/README.md
Recreated the #435 PR which fixes issue #432.
-----
Aligns the Policy text specification for timestamps to the Provider and Agency
APIs, which use integer milliseconds from Unix epoch.
Fixes issue #432.
Fixes mismatch of string vs. number for timestamps.
Technically, yes, but in reality I'm not sure.
The `mds-core` reference implementation already defined timestamps as numbers:
https://github.com/openmobilityfoundation/mds-core/blob/09930c89ea4c71684140aa0046ba9727be40bd79/packages/mds-types/index.ts#L144
That being said, if other implementations exist that were using strings it's possible there will be breakage.
* `policy`
N/A
> Policy: use a consistent definition for timestamps (recreation)

- .github/PULL_REQUEST_TEMPLATE/release-candidate.md
- .github/PULL_REQUEST_TEMPLATE/release-final.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- ReleaseGuidelines.md
- ReleaseNotes.md
- agency/get_vehicle.json
- agency/post_vehicle.json
- agency/post_vehicle_event.json
- agency/post_vehicle_telemetry.json
- provider/README.md
- provider/auth.md
- provider/dockless/events.json
- provider/dockless/status_changes.json
- provider/dockless/trips.json
- provider/dockless/vehicles.json
- schema/templates/agency/get_vehicle.json
- schema/templates/agency/post_vehicle.json
- schema/templates/agency/post_vehicle_event.json
- schema/templates/agency/post_vehicle_telemetry.json
- schema/templates/common.json
- schema/templates/provider/status_changes.json
- schema/templates/provider/trips.json
- schema/templates/provider/vehicles.json
Per issue [#7](https://github.com/openmobilityfoundation/governance/issues/7) in the Governance repo, this PR finds all mentions of "master" in the `dev` branch and replaces it with "main".
> Updating references from 'master' to 'main'

- agency/README.md
Thank you for your contribution!
*For most Pull Requests, the target branch should be [**`dev`**](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev). Please ensure you are targeting **`dev`** to avoid complications and help make the Review process as smooth as possible.*
The telemetry spec only says that when new telemetry are successfully received, the server should:
> Responds with number of successfully written telemetry data points and total number of provided points.
But the spec does not specify how those two numbers should be written.
A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking …
> Clarify success response for telemetry update

- policy/examples.md
Rearrange the Policy API's speed-limit examples from most specific to least specific, per the API's ["order of operations"](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev/policy#order-of-operations) system.
Right now, these two examples are in (least specific, most specific) order, which should mean that the "Venice Beach on weekend afternoons" Rule **never** applies to any vehicle, which seems like probably a mistake!
* `policy`
> Rearrange the Policy API's speed limit example

- general-information.md
> Removing OPTIONS version negotiation

- general-information.md
- provider/README.md
- provider/events.json
- provider/status_changes.json
- provider/trips.json
- provider/vehicles.json
- schema/generate_schemas.py
Resolves #428 following @jfh01's suggestion to use GeoJSON Foreign Members. Relates pretty closely to the open PR #427, and is dependent on that being merged first.
* `provider`
> Add stop references to trips and status_changes

- ReleaseNotes.md
This is a draft of the 1.0.0 release notes file for review.
> Release Notes for 1.0.0

- general-information.md
- schema/templates/common.json
Also clean up a few duplicate table entries.
> Add 'unspecified' events to some schema states

- README.md
The state of practice doc has moved since we last updated the v1.0 readme. It's [here](https://github.com/openmobilityfoundation/privacy-committee/blob/main/products/state-of-the-practice.md).
> Update State of Practice link

- agency/get_stops.json
- agency/get_vehicle.json
- agency/post_stops.json
- agency/post_vehicle.json
- policy/README.md
- policy/examples.md
- policy/examples/README.md
- policy/examples/idle-time.json
- policy/examples/metered-parking-fees.json
- policy/examples/per-trip-fees.json
- policy/examples/prohibited-zone.json
- policy/examples/provider-cap.json
- policy/examples/speed-limits.json
- policy/examples/vehicle-row-fees.json
- policy/policy.json
- provider/README.md
- provider/events.json
- provider/status_changes.json
- provider/stops.json
- provider/trips.json
- provider/vehicles.json
- schema/README.md
- schema/agency.py
- schema/common.py
- schema/generate_schemas.py
- schema/policy.py
- schema/provider.py
- schema/templates/common.json
- schema/templates/policy/policy.json
- schema/templates/provider/trips.json
JSON Schema describing MDS 1.0 Policy.
The examples have been pulled out into distinct files in a subdirectory and updated to pass schema validation.
Closes #389.
> Policy JSON Schema

- geography/README.md
- geography/examples/README.md
- geography/examples/distribution-zone-8.json
- geography/examples/geographies.json
- geography/examples/municipal-boundary.json
- geography/examples/no-ride-zone.json
- geography/examples/operating-area.json
- geography/examples/slow-ride-zone.json
- geography/examples/stop.json
- policy/README.md
A policy object contains a property published_date which is the exact
same thing as a geography object's publish_date. These should therefore
also have the same name to prevent errors and confusion.
---
name: Default
title: Rename publish_date to published_date for a geography object
---
1. Target …
> Rename publish_date to published_date for a geography object

- provider/README.md
In MDS 0.4.x we request trips and status changes for a given hour. A provider may have no data to report for the requested hour for multiple reasons, including:
- The hour has not yet fully passed
- The provider was not operational in the region during the hour
- The provider has not yet completed processing that hour's data
- No trips or events occurred during the hour
Differentiating the last two reasons is particularly important because it lets consumers of APIs know whether or not they need to re-request the hour at a later time. A successful 200 response with an empty list of data clearly communicates that the provider has nothing to report for that hour and that it's not necessary to try again later. Having this behavior consistent across providers would help us at Populus spend …
> Clarify trips and status changes response behavior

- general-information.md
- policy/README.md
- policy/examples/README.md
- policy/examples/required-parking.json
Consolidated updates to stops from the community across a few issues and discussions:
- Stops in policy - Add optional stops to rules (like geographies). If stops then geography ID required. #554
- Required stops example addition using current policy rules #554
- Optional stops image #555
* `agency`
* `policy`
* `provider`
> Stops Updates for Release

- general-information.md
- geography/README.md
Addressing multiple Issues and conversations around geographic parts of the release and /geography:
- Roll policy types into new geo type (geofence/policy_zone) #588 
- Retire date optional #590 
- Allowing  Polygons - Need to clarify no points or specify in spec a buffer around any points. Geographic data in general info - polygon. Point in route for stop. Connect to geography for stop as a feature collection. Change example from point to polygons for stops in Geography. Change location field to describe polygon or point (just point now).  
* `agency`
* `policy`
* `provider`
> Geographic Updates for Release

- agency/README.md
As an agency, when receiving a batch of telemetry data including unregistered devices, there is currently no official way to let the provider know why the corresponding telemetries were rejected. This makes it complicated for the provider to automate the detection and resolution of this problem.
Adapt the `unregistered` error existing in the Agency/event endpoint to Agency/telemetry.
No, not breaking : we are just adding a new error type. 
For which spec is this feature being requested?
* `agency`
The current workaround we are using is to return a bad_param error on parameter `device_id`, Listing the unregistered ids in the error description: `A validation error occured. Unregistered devices: UUID1, UUID2, etc.`.
> Agency/telemetry: add `unregistered` error

- agency/get_stops.json
- agency/get_vehicle.json
- agency/post_stops.json
- agency/post_vehicle_event.json
- agency/post_vehicle_telemetry.json
- policy/policy.json
- provider/events.json
- provider/status_changes.json
- provider/stops.json
- provider/trips.json
- provider/vehicles.json
- schema/templates/common.json
The goal is to prevent the easy to make mistake of using a second
timestamp instead of a millisecond timestamp.
This PR implements issue #645
> Add minimal value to all timestamp json definition

- provider/README.md
The trips and status changes endpoints are expected to return HTTP 404 responses when data "does not exist". I'm trying to clarify that that means the future and hours when the provider was not in operation in the municipality. For past hours during which the provider was operating but nothing happened they should return empty arrays of trips or status changes.
I'm guessing, but not totally sure, that this was the original intent.
* No, …
> Clarify "data does not exist" vs empty data for trips and status changes

- policy/README.md
- policy/examples/README.md
- policy/examples/tiered-parking-fees-per-hour.json
- policy/examples/tiered-parking-fees-total.json
There has been a lot of discussion recently around supporting duration based fees in MDS Policy (see #631), but I'll try to put a short explanation in this PR.
Say, for example, a city wishes to have a parking zone which costs $2 for the first hour, $4 for the second hour, and $10 for every hour onwards (note, these exemplar parking fees are rather high 😅 ); at the moment, this is not supported by the `rate` rule type. Luckily, MDS Policy has the `time` rule type, which can perfectly handle this case! We can leverage Policy's short-circuiting behavior by creating `time` rules which start off with higher time ranges, and increasingly slice down into lower ranges. In this particular example, we could order our rules as such:
1. Time maximum 2 hrs, fee $10 (any vehicles which dwelled for …
> Tiered Dwell Time with Rates

- policy/examples/idle-time.json
- policy/examples/metered-parking-fees.json
- policy/examples/per-trip-fees.json
- policy/examples/prohibited-zone.json
- policy/examples/provider-cap.json
- policy/examples/required-parking.json
- policy/examples/speed-limits.json
- policy/examples/tiered-parking-fees-per-hour.json
- policy/examples/tiered-parking-fees-total.json
- policy/examples/vehicle-row-fees.json
- schema/templates/policy/policy.json
This PR is to resolve #599, which highlighted inconsistencies between the spec and JSONSchema definitions & examples. The approach taken was to leave the spec as-is (for now) in order to be non-breaking, and to update the JSONSchema definitions & examples to align with the spec in its current state.
* `policy`
For MDS 2.0, we may want to explore structuring this in accordance with the JSONAPI spec, e.g.
```
{
"data": {
"type": "policies",
"attributes": {
}
}
},
```
> Align Policy JSON Schema & Examples with spec

- policy/README.md
- policy/policy.json
- schema/templates/policy/policy.json
MDS does not currently specify whether Policy Rule `minimum` and `maximum` values are considered within bounds when evaluating whether something matches the rule (in other words, whether the rule bounds are a open, closed, or half-open interval). This PR adds new fields to Policy Rules that allow users to individually specify the treatment of the `minimum` and `maximum` values.
The new fields are called `inclusive_minimum` and `inclusive_maximum`. They are boolean fields that both default to true.
I don't think this is breaking, but it does define that by default rule `minimum` and `maximum` are considered within the rule bounds, which could potentially break interpretation of existing policy rules.
* `policy`
This is an alternative PR to #677, we should pick one or the …
> Allow users to specify rule min/max treatment

- policy/README.md
- policy/examples/README.md
- policy/examples/tiered-parking-fees-per-hour-in-bounds.json
- policy/policy.json
- schema/templates/policy/policy.json
This is implementing my proposal from #666. The `rate_applies_when` field allows people constructing policy rules with attached rates to specify when the rate is applicable: is it when something is within the rule bounds or when it is outside of them? The `rate_applies_when` when field may take on the values `in_bounds` and `out_of_bounds`. It is used in conjunction with the rule `minimum` and `maximum` fields. It defaults to `out_of_bounds`.
I also used this PR to bring the Policy JSON schema and an example policy up-to-date following the merger of #658.
* I'm not sure
This field is optional so it doesn't break in that sense, but having a defined notion of when rates apply could change the interpretation of existing policies.
* `policy`
The MDS policy spec does not currently specify when …
> Add a rate_applies_when field to Policy Rules

- general-information.md
- schema/templates/common.json
Per issue #692, working group discussions, and the fact that London using this vehicle type, we are adding as an optional new type to MDS.
* `agency`
* `policy`
* `provider`
We will address more changes in MDS 2.0.0 when we add new modes and align with more changes in GBFS.
> Add 'cargo_bicycle' vehicle type

- providers.csv
> Add TukTuk provider

- providers.csv
Add Scoot and Revel provider_id values to providers.csv.  Scoot and Revel have been operating scooters and mopeds, respectively in San Francisco for a few years using these values for provider_id.
None - providers.csv file
> Add Scoot and Revel to providers.csv

- policy/README.md
Fixes metadata field which is not an array, removes required_data_specs and required_apis fields which are not at this level of the JSON.
> Fixes to Requirements documentation

- agencies.csv
Update agencies.csv to include link SFMTA requirements file and change the agency name from "San Francisco" to "San Francisco Municipal Transportation Agency.
A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint).
> Update agencies.csv to include SFMTA requirements URL

- providers.csv
---
name: Default
title: Request to add BCycle to Providers List
---
1. Keep the *"Allow edits from maintainers"* button checked to help us resolve some issues for you.
1. Be …
> Request to add BCycle to Providers list

- provider/README.md
The `/reports` spec has column names in an inconsistent format.  `StartDate` is CamelCase, but all other column names are plain English.  We use snake case elsewhere, and even do so farther down in the `/reports` spec when discussing `special_group_type`, so I went with that.
Technically this is a breaking change, but the `/reports` endpoint is still beta so it's not clear how big of a deal that is.  That said, the goal would be for this change to be incorporated into 2.0, which allows for breaking changes anyway.
* `provider`
N/A
> `/reports` column names

- provider/README.md
Following the discussion and [meeting earlier this year](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2022.07.07-(MDS-Working-Group)) on #672, add 'adaptive_scooter' as a special_group_type to reflect SFMTA's use of this in the Reports endpoint for its [scooter program](https://www.sfmta.com/blog/adaptive-scooters-coming-street-near-you).
Also, in our use of Reports, we've found that adding provider_id is necessary so we know which company the report is from.  It would be better if the providers included this directly. 
A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking …
> Reports - Add provider_id and adaptive_scooter as a special group type

- general-information.md
- provider/README.md
The spec currently requires the `/reports` endpoint to be queried with media-type `application/vnd.mds+json` in the `Accept` header.  But the endpoint returns a CSV, not JSON, so this is a bit confusing.  This PR suggests a different approach (though it has its own drawback since `csv` is not a standard media-type suffix).
This is a breaking change.  The intent is for this to be included in MDS 2.0.
* `provider`
See the discussion from https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2022.07.07-(MDS-Working-Group) and the discussion at https://github.com/openmobilityfoundation/mobility-data-specification/issues/672
> Reports - Accept header media-type

- modes/car-share.md
- modes/delivery-robots.md
- modes/event_types.md
- modes/micromobility.md
- modes/passenger-services.md
- modes/vehicle_states.md
---
name: Replace unknown state
about: Replace unknown state with two new states so that vehicles can definitely be yes/no in PROW.
title: Replace unknown state
---
1. Keep the *"Allow edits from …
> Replace unknown state

- general-information.md
- provider/README.md
This addresses #748 by adding a definition of a "trip" to the general-information.md file. The definition is meant for the purposes of analysis in particular, and not for filtering which data points are exchanged as part of MDS endpoints.
I wasn't sure on the exact right spot for this since I hadn't seen anything like this done before in MDS, but I'm open to suggestions on that and the wording of the definition itself.
I don't consider this a breaking change since it doesn't effect the data interchange at all, only downstream analytics, but I might be missing something.
* `agency`
* `policy`
* `provider`
In a way, all of these and none of these. 🤔
> Define a "trip" for the purposes of analyses

- general-information.md
Mainly the wording around Bulk Responses and Error Messages to be more general.
Saving this file in my IDE also ran it through markdownlint so got a few formatting cleanups, removed extra whitespace and unused link refs, etc.
> Clean ups in the General Info file

- provider/README.md
In older versions of MDS data was nested under a `data` key in provider API responses, so trips data would e.g. be response['data']['trips']. This ended up reflected in the docs where each section would have a label like "`data` Payload" describing what was under the `data` key in the payload.
In MDS 2.0 this nesting was removed, `trips` is now a top level key in the response from provider trips endpoint. However, the docs were not updated to remove the word "data" from the payload descriptions, leading to potential confusion for readers of the documentation. This PR changes "`data` Payload" to "Payload" throughout the provider README to bring it in line with the spec.
* No, not breaking. This is a documentation only change that brings the docs more in line with the spec.
Which spec(s) …
> Remove word "data" from provider response payload descriptions

- provider/README.md
The example API response for the /vehicles/status endpoint had the data key as 'vehicles' when it is in fact 'vehicles_status'. See OpenAPI spec [here](https://openmobilityfnd.stoplight.io/docs/mds-openapi/800dc7d0f0420-vehicles-status).
* No, not breaking. This only brings the documentation in line with the spec.
* `provider`
> Fix JSON key in /vehicles/status example response

- provider/README.md
The description of the Provider vehicles endpoints was never really updated in the MDS 1 -> 2 transition so this rearranges and clarifies some things now that there are two vehicle information endpoints, one for static information like vehicle/propulsion type and another for realtime status. These changes are mostly rearranging/clarifying, but there is one 
major addition to the description of the `/vehicles` endpoint describing that when called without a device ID it is expected to return every vehicle ever deployed in a jurisdiction. This closes #879.
* No, not breaking. This makes no changes to the spec format, only clarifies content expectations.
* `provider`
See also #879.
> Clarify which vehicles to include in the `/vehicles` endpoint

- provider/README.md
This one example of the /vehicles/status response payload had the wrong payload key, creating confusion for readers.
* `provider`
N/A
> Fix vehicle status payload key

- data-types.md
Added conditionally required fields and language
---
name: Default
title: <Make some Fields in Stops Conditionally Required>
---
1. Keep the *"Allow edits from maintainers"* …
> Conditionally Require Fields in MDS Stops Endpoint Related to Station Based Program/SLA Metrics
