- mobility-data-specification.md
Also added a bit of consistency by changing all instances of `ZULU` to `UTC`.
> Minor cleanup and spelling fixes

- provider/README.md
added a few fields, added projection for geographic data
> Some updates to provider/readme

- agency/README.md
Minor changes.   Fixed links as reported by @thekaveman.
> Fixed Links, Minor Name Changes

- meta.md
We suggest that you JSON API but don't explicitly call out how to do pagination. This creates a root level document, `meta.md` to handle all pagination, auth and other info applicable to provider and agency.
> Pagination fix. Fixes #20

- provider/README.md
* The Device_Type enum only made it into provider. This matches it into agency.
> adding enums back into provider, matching to agency

- agency/README.md
Added messages that supports the following Workflow:     
1.  Register Vehicle (register the vehicle with the agency)
2. Deploy Vehicle (put a vehicle on the street)
3. Start Trip -  Tell the Agency that a trip has started
4. Update Telemetry - Update data within an opened trip
5. End Trip - Tell the Agency that a trip has ended
> Updated messages to enhance failure tolerance

- agency/README.md
The table for response wasn't showing as a table. Now it is.
> Clean up markdown formatting

- agency/README.md
- provider/README.md
> Simple linting fixes

- agency/README.md
Just some minor cleanup I noticed while working on #85
> Minor cleanup to formatting of unique_id in Agency API.

- provider/README.md
> Clarifying timestamp format

- provider/README.md
> Clarifying location type

- provider/README.md
> fix optional based on device. 

- providers.csv
Otherwise these are interpreted as part of the CSV "values"
> Remove extra spaces

- providers.csv
For validation tool purposes, it is helpful to standardize this as well.
> Elimate trailing slashes in providers.csv

- agency/README.md
> update update_vehicle_status to use standard post

- README.md
@WheresHJ suggested that we link our various implementations and associated repos.
> Update README to show associated python libraries

- provider/README.md
And removing a duplicate line of text. And some wording cleanup while I'm at it.
> Fixing newlines again

- generate_schema/provider/status_changes.json
- generate_schema/provider/trips.json
- provider/status_changes.json
- provider/trips.json
This is a PR for the non-breaking JSON Schema fixes identified in #128 and elsewhere.
> Schema fixes

- README.md
- ReleaseGuidelines.md
- ReleaseNotes.md
For #129 
Early draft. The checklist is definitely not complete yet.
> Release guidelines

- README.md
Hi,
This is a pull request to add BlueSystems `midas` open source project to the list of related projects.
Kind Regards.
> Add BlueSystems `midas` to related projects

- provider/auth.md
Update `auth.md` with authentication requirements.
> Authentication Requirements. Fixes #171

- agency/README.md
Adds two missing initial event states and resolves clarification for #115.
> Fixing two missing initial event states.

- agency/README.md
Consistent naming/format and remove unneeded provider_id parameter.
> Cleaning up service_areas endpoint

- agency/README.md
Also replacer "UUIDv4" with "UUID4", as is convention
> Update definition of timestamp to match provider

- agency/README.md
to make consistent with Provider
> drop UUID4 requirement in favor of simply UUID

- agency/README.md
> specify behavior for GET /vehicles with no device_id

- providers.csv
https://www.micromobility.com/
> Added Bolt to list of MDS providers

- providers.csv
Need to update SPIN API URL based on [docs](https://web.spin.pm/datafeeds)
[  ] Yes, breaking
[ * ] No, not breaking
[  ] I'm not sure
**`Provider` or `agency`**
[  ] `provider`
[  ] `agency`
[ * ] both
> Update Providers.csv with corrected SPIN API URL

- README.md
Updates `README.md` to have a clear versions section, notes that the reader might not be on a released version, links to master / all version pages. 
**Is this a breaking change**
* [_] No, not breaking
**`Provider` or `agency`**
* [_] both
> add readme version notes. #288

- .github/ISSUE_TEMPLATE/feature-request---proposal.md
- .github/pull_request_template.md
**Explain pull request**
Makes the lists render as bullets. Markdown fixes.
> Template Cleanup

- providers.csv
Adding Sherpa to the list of scooter providers in LA 
* [X ] No, not breaking
* [X ] `provider`
website is TBD
> add Sherpa to providers.csv

- providers.csv
correcting sherpa gbfs api url in preparation for launch
> update sherpa gbfs api url

- ReleaseNotes.md
> update release notes for 0.3.2

- providers.csv
https://mds.bird.co/gbfs/platform-partner/sherpa-la/los-angeles/free_bike_status.json
> update sherpa name and gbfs url

- README.md
This PR incorporates PRs #320/#323 from @jpayne00, along with changes to address @thekaveman and @karcass's questions.  The PR is slightly out of date already given the launch of the OMF, but better to get this cleanup done now and a subsequent one regarding OMF. 
* both
Hopefully, this address the issues that @jfh brough up in #287. If not, we can do another PR as well.
> Readme updates 2019

- providers.csv
Please provide a clear and concise reason for this pull request and the impact of the change
> Add OjO Electric as a provider

- README.md
> Adding info for Santa Monica's Pilot

- README.md
Add Austin to list of cities using MDS and fix nearby typos.
No.
None. README.md only.
> Add Austin to Cities List

- agency/README.md
I just added a backtick that made me crazy.
> Small typo

- README.md
Move contribution related section to the top of the page. This will help following calls and contributing more straightforward.
* None
[This PR is related to issue #364](https://github.com/CityOfLosAngeles/mobility-data-specification/issues/364)
> Promote contributing in README.md

- README.md
Re-order so the "Add your city" link is at the bottom of the list of cities.
> minor fix following #366

- README.md
List of features easier to read without redundant "To".
Neither, text only.
> Cleaning up a bit of grammar/wording in README for clarity

- provider/README.md
- provider/dockless/trips.json
- schema/templates/provider/trips.json
MDS is now being used outside of the United States, therefore, Standard Cost / Actual Cost need internationalization, per #91. 
* `provider`
> Currency fix

- providers.csv
Add a new provider (MOVO)
`provider`
> Add MOVO provider

- .github/ISSUE_TEMPLATE/feature-request---proposal.md
- .github/pull_request_template.md
Update the issue and PR templates to call out the `policy` spec specifically.
This PR should not be merged until after #382 is merged.
> Updating templates to include policy spec

- providers.csv
Please provide a clear and concise reason for this pull request and the impact of the change
Operator Baus launching as a Bird Platform Partner.
* Yes, breaking
* **No, not breaking**
* I'm not sure
* **`provider`**
* `agency`
* both
Adding information for new provider Baus.
> Update providers.csv, adding Baus

- ReleaseNotes.md
Happy Halloween! Here's the 0.4.0 release notes!
> update release notes

- providers.csv
changed CLEVR mds url
* `provider`
> change CLEVR url

- providers.csv
fix CLEVR mds url
* `provider`
> fix CLEVR mds url

- providers.csv
This PR adds new MDS provider
* no one
> Add Bolt Technology as MDS provider

- providers.csv
Add Grin provider
* `provider`
> Add Grin provider

- providers.csv
Adding [Dott](https://ridedott.com/) to the provider list.
* `provider`
Not applicable.
> Add Dott provider entry

- README.md
Adds a link to documentation about the different MDS APIs. 
This is (hopefully) a clean PR that replaces the garbage fire that was #448. 
> Added link in README to the Understanding MDS APIs wiki page 

- provider/README.md
* remove extra spaces at end of line
* proper list formatting
* remove inline HTML
* correct heading level
* `provider`
> Minor markdown cleanups

- ReleaseGuidelines.md
This is a minor update to the release guidelines
N/A
This is a documentation update
> Add the currently supported MDS versions

- providers.csv
Adding Superpedestrian MDS here due to vendor request.
Let me know if there's anything else.
> Superpedestrian MDS feed

- agency/README.md
- agency/get_stops.json
- agency/post_stops.json
- agency/post_vehicle_event.json
- agency/post_vehicle_telemetry.json
- agency/put_stops.json
- general-information.md
- provider/README.md
- provider/events.json
- provider/status_changes.json
- provider/stops.json
- provider/trips.json
- provider/vehicles.json
- schema/generate_schemas.py
- schema/templates/agency/get_stops.json
- schema/templates/agency/post_stops.json
- schema/templates/agency/put_stops.json
- schema/templates/common.json
- schema/templates/provider/stops.json
* Agency `GET /stops`
* Agency `POST /stops`
* Agency `PUT /stops`
* Provider `GET /stops`
> JSON Schemas for Stops

- providers.csv
---
name: Add Pony as Provider
title: Add Pony as Provider
---
1. Keep the *"Allow edits from maintainers"* button checked to help us resolve some issues for you.
1. Be ready to …
> add pony provider

- providers.csv
---
name: Add two new providers
---
Adding Zisch & Seven Group as Providers
> Add Seven Group and Zisch as Providers

- policy/README.md
Added an Update Frequency section to Policy to clearly state that this needs to be communicated by agencies to providers so expectations are set beforehand.
* `policy`
See Issue #567 for context, which was created based on lack of clarity in Policy around update frequency expectations.
> Added update frequency policy section

- providers.csv
Adding a new provider per the email request of the provider.
* N/A
> Add Boaz Bikes Provider

- providers.csv
Adding new provider VeoRide INC.
N/A
> Update providers.csv with VeoRide

- schema/templates/provider/vehicles.json
Updating the schema template to accommodate changes made in #665 
* `provider`
N/A
> Add all vehicle states to schema template

- providers.csv
Adding helbiz to the list of providers
None
/
> Adding Helbiz to providers.csv

- agencies.csv
---
name: Ride Report
title: Added PBOT Requirements API url to agencies.csv
---
> Added PBOT Requirements API url

- providers.csv
**name:** 
Adding Yego Operator in the operator list
**Is this a breaking change**
**Which spec(s) will this pull request impact?**
None
> Adding Yego operator

- providers.csv
---
name: Add Leo and Go provider
about: Leo&Go is a car sharing service (free floating) operating in Lyon (France) using the Vulog Mobility solution to operate their service.
title: Add Leo and Go provider
---
1. Target [**`dev`**](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev) branch. Please ensure you are targeting **`dev`**, not …
> Add Leo&Go provider

- providers.csv
name: Add Tembici Provider
about: Add new provider in providers.csv
title: Add Tembici Provider
https://www.tembici.com.br/
---
1. Keep the *"Allow edits from maintainers"* button checked to help us resolve …
> Add Tembici Provider

- modes/micromobility.md
1. Keep the *"Allow edits from maintainers"* button checked to help us resolve some issues for you.
1. Be ready to resolve any merge conflicts before we approve your Pull Request.
1. Have an up to date …
> fix spelling error

- policy/README.md
This is a response to this issue: https://github.com/openmobilityfoundation/mobility-data-specification/issues/668
A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint).
* `policy`
> Updating policy query parameter language to be clearer.

- agency/README.md
---
name: Better Telemetry error handling
title: Better Telemetry error handling
---
The purpose of this change is to provide a better and clearer description of expected error behavoir of the batch telemetry endpoint.
See issue #703 for further description
* Yes, breaking
Most likely a breaking change as the error behavoir of implementations has to change, but depends on the current error behavior implementation
* `agency`
> Better Telemetry error handling

- data-types.md
Remove `hdop`, which is superseded by `horizontal_accuracy`
> remove hdop

- data-types.md
* Corrects some field types / names
* Remove trailing whitespace
* Remove unused markdown link references
> Fix: clean up data types

- geography/README.md
* All endpoints are public -- ensure response codes reflect that
* Correct the type of GeoJSON (to `FeatureCollection`)
* Make the change to `last_updated` #842 (still need to do so for Policy)
* Update some links, API naming
* Markdownlint
> Clean ups in Geography 

- providers.csv
---
name: Default
title: <Insert Title>
---
1. Keep the *"Allow edits from maintainers"* button checked to help us resolve some issues for you.
1. Be ready to resolve any merge …
> Add GBFS endpoint for Whoosh

- providers.csv
---
name: Default
title: Add DeutscheBahnConnect
---
Add new Provider.
* `provider`
> Add DeutscheBahnConnect

- providers.csv
---
name: Mitch Vars
about: Update to  providers.csv
title: Add Flamingo
---
Adds Flamingo to providers.csv
> Add Flamingo
